#1) Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Solution:-

NumPy (Numerical Python) is a fundamental library in python used fr numerical and scientific computing. Its primary purpose is to provide support for large multi-dimensional arrays and matrices, along with the collection of mathematical functions to operate on these array efficiency.

Advantages of NumPy:-

1) Efficient Data Structures:- NumPy arrays are more compact and efficient than python lists, especially when dealing with large datasets. The arrays are stored in contiguous memory, allowing faster access and manipulatin of data.

2) Fast Computation:- NumPy is implemented in C, making it much faster than Python's native listsfor numerical operations. It supports element-wise operations on arrays,which means it can perform batch computations on data, speeding up processes like matrix multiplication and linear algebra.

3) Broadcasting:- NumPy enables broadcasting, a mechanism that allows operations between arrays of different shapes. This eliminates the need for explicit looping and reshaping, reducing both the complexity and executing time of the code.

4) Integratin with other liberaries:- Many other scientific liberaries rely on NumPy as their core. This makes NumPy an essential tool in the Python data science ecosystem.

5) Extensive Mathematical Functions:- NumPy provides an extensive collection of built-in mathematical functions as trignometric, statistical, and algebric functions, optimised for perfrmance.

6) Support for mathematical arrays:- It supports multi-dimensional arrays(n- dimensional), allowing scientists and analysts to perform operations on large datasetslike images, signal or other forms of complex data.


Role of NumPy in enhancing capabilities of python in mathematical operations:-

1) Efficient Array Handling:-

NumPy Arrays (ndarray)

* At the core of the Numpy is the ndarray (n-dimensional array), which allows for the efficient storage and the manipulation of homogenous(some data type) multi dimensional data. These arrays are more memory efficient and faster than Python's native lists, as they store data in a continguoous block of memory, reducing overhead.

Advantages of ndarray:

* Fixed size:- Unlike Python's lists, NumPy arrays have a fixed size once created, which avoids dynamic resizing and overhead associated with lists.

* Homogeneous elements:- NumPy elements stores elements of the same type, which avoids the need for type checking at runtime and allows for optimised memory layouts.

* Contiguous Memory Layout:- The data is stored in contiguous memory locations, which spreads up operations by reducing memory access times.

Example:




In [ ]:
import numpy as np
l = [1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

2) Vectorized operations:- One of the most important function of NumPy is Vectorization. In NumPy, operations can be applied element-wise n entire arrays without the need for explicit loops. This allows pPython's code to run faster and makes it more concise and readable.

Element-wise Operatins:

NumPy allows for operations like addition, substraction, multiplication, division and more to be applied on all elements of an array simultaneously, bypassing the need for Python's loops, which are slower.

Example:



In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
a+b

array([ 7,  9, 11, 13, 15])

3) Broadcasting:-

Broadcasting is a powerful mechanism in NumPy that allows arrays of different shapes to be used together in arithmatic operations. NumPy automatically adjusts the shapes of the arrays without making explicit copies enabling concise and efficient code.

Example:

In [ ]:
a = np.array([1,2,3])
b = 10  # Scaler value
a*b # Broadcasting

array([10, 20, 30])

4) Advanced Indexing and Slicing:-

NumPy allows for advanced indexing and slicing, making it easier and faster to access and modify specific parts of arrays. The capability enhances Python's built-in list slicing functionality and prvide more flexibility.

Basic Slicing: Just like Python lists, NumPy arrays support slicing, but with more options, including multi-dimensional slicing.

Example:

In [ ]:
array = np.array([[1,2,3,], [4,5,6], [7,8,9]])
sub_array = array[0:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


Boolean Indexing:

In [ ]:
arr= np.array([1,2,3,4,5])
filtered_array = arr[arr>2]
print(filtered_array)

[3 4 5]


5) Support for multi-dimensional arrays:-

Unlike Python lists, which are typically used for one-dimensional or simple nested data, NumPy efficiently handles n-dimensional arrays, making it highly useful for tasks involving multi-dimensional data (e.g. images, 3D geomatry, or scientific data).

Multidimensional array creation:-

NumPy arrays can be created with mre than ne dimension easily, enabling complex data manipulations across various dimensions.

Example:

In [ ]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


6) Mathematical and Statistical Functions:-

NumPy comes up with an extensive suit of optimized mathematical and stastical functins which are essential for scientific cmputing.

Mathematical Operations:-

NumPy provides functions for a wide range of mathematical operations like trigonomatry (sin,cos), exponential and logarithmic functions, power functionsetc.

Linear Algebra:-

NumPy includes functions for matrix operations through np.linalg.

Exaple;



In [ ]:
A = np.array([[1,2,], [3,4]])
B = np.array([[5,6], [7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

7) Memory efficiency and manipulation:- NumPy supports memory- mapped files, which allow large arrays to be stored on disk and loaded into memory when needed, rather than loading the entire dataset at once. The feature is crucial when working with datasets too large to fit into RAM.

Array Manipulation:-

Functions like reshape(), transpose(), concatenate(), and rearranging of data into memory, without copying the underlying data, making it both fast and memory-efficient.


NumPy enhances Python's numerical capabilities by providing highly efficient data structures , optimizing memory usage, offering vectorized and broadcasted operations, and supplying a comprehensive range of mathematical functions.

#2) compare np.mean() and np.average() function in NumPy.When would you use one over the other?

Solution:

In NumPy, both np.mean() and np.average() are used to compute the average of an array, buth they differ in functionality. As:

1) Basic Functionality:-

* np.mean():

* Computes the atithmatic mean (average) of the elements along a specified axis or the entire array.

* It does not consinder any weights: all elements are treated equally.





In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
result = np.mean(arr)
print(result)

3.0


*np.average():

* Computes the weighted average of an array. It can take an additional weight parameter that allows you to assign different weights to different elements.

* If no weights are provided, np.average() behaves like np.mean(), giving an unweighted average.

Example:

In [ ]:
arr = np.array([1,2,3,4,5])
weights = np.array([1,2,3,4,5])
result = np.average(arr, weights =weights)
print(result)

3.6666666666666665


2) Weights Parameter:-

* np.mean():

Does not support weights. It always computes the simple arithmatic mean.

*np.average():

Supports an optional weight parameter. If provided the functin calculates a weighted average, where each element contributes to the final average according to its corresponding weights.



In [ ]:
arr = np.array([22,98,65,54,12,30])
weights = np.array([1,2,3,4,5,6])
result = np.average(arr,weights=weights)
print(result)

41.38095238095238


3) Returned Result:

* np.mean():

returns a single value (the mean) or an array if computed along a specific axis.

* np.average():

Returns the weighted average as a single value or along an axis. Additionally, it can returned the sum of the weights when you set returned=True.

In [ ]:
avg, sum_weights = np.average(arr, weights=weights, returned=True)
print(avg, sum_weights)

41.38095238095238  21.0


4) Performance:

* np.mean():

Simpler and potentially faster whe no weights are involved, as it only computes the sum of elements divided by the count.

*np.average():

Slightly more computationally intensive when using weights since it involve multiplying each element by its correponding weight and then normalizing by the sum of weights.

Use cases:

1) np.mean() Use case:

Calculate the average temperature across a week where are days are equally important.

In [ ]:
temperatures = np.array([23,25,22,25,21,23,24,22])
avg_temperature = np.mean(temperatures)
print(avg_temperature)

23.125


2) np.average() Use Case:

Calculating a student's weighted grade where different exams or assignments contribute differently to the final grade.

In [ ]:
grades = np.array([85,76,90,65,88,76])
weight = np.array([0.2,0.3,0.5,0.1,0.2,0.4])
weighted_avg = np.average(grades, weights=weights)
print(weighted_avg)

79.19047619047619


np.mean() is ideal for the cases where all data points are equally important, and you need a simple arithmatic mean whereas np.average() should be used when dealing with weighted data, where certain elements have more significance in the overall calculations.

#3) Describe the methods for reversing Numpy array along different axes. Provide examples for 1D and 2D arrays

Solution:

Reersing a NumPy array along different axes can be achieved using slicing or the np.flip() function. Both methods allow you to reverse an array along a specified axes.

1) Reversing a 1D Array:

For a !D array, reversing simply means reversing the order of the elements.

Method 1: Using Slicing;





In [ ]:
arr_1d = np.array([1,2,3,4,5])
reversed_1d = arr_1d[::-1]
print(reversed_1d)

[5 4 3 2 1]


Using np.flip(): For specific axis.

In [ ]:
reversed_1d_flip = np.flip(arr_1d)
print(reversed_1d_flip)

[5 4 3 2 1]


2) Reversing a 2D Array:

For a 2D array, you can reverse along different axes:

Rows (axis= 0): This will reverse the oreder of the rows.


Columns(axis= 1): This will reverse the order of the columns.

Both axes: This will reverse the array both row-wise and column-wise.

Method 1:Using slicing

*Reverse Rows(axis=0):

In [ ]:
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
reversed_2d_rows = arr_2d[::-1,:]
reversed_2d_rows

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

* Reverse Columns (axis=1):


In [ ]:
reversed_columns = arr_2d[:,::-1]
reversed_columns

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

* Reverse both axes( rows and columns):

In [ ]:
reversed_both = arr_2d[::-1, ::-1]
reversed_both

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

Method 2:Using np.flip()

* Reverse Rows:

In [ ]:
reversed_rows_flip = np.flip(arr_2d, axis=0)
reversed_rows_flip

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

* Reverse Columns(axis=1):

In [ ]:
reversed_column_flip = np.flip(arr_2d, axis=1)
reversed_column_flip

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

* Reverse both axes:

In [ ]:
reversed_flip_both = np.flip(arr_2d, axis=(0,1))
reversed_flip_both

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

#4) How can you determine the datatypes of elements in a NumPy array? Discuss the importance of data types in memory management and performance?

Solution:

In NumPy, the datatype of the elements in an array is represented by the dtype attribute. This can be used to check the type of data stored in the array. NumPy supports ab wide range of datatypes such as int32,float64,bool, etc.

Example of determining Datatypes:


In [ ]:
arr = np.array([1,2,3,4,5]) # Create an array of integers
arr.dtype                   # Check the datatype of the array of elements

dtype('int64')

In [ ]:
arr1 = np.array([2.3,2.4,5.6,8.5])
arr1.dtype

dtype('float64')

In [ ]:
arr2 = np.array(["ram", "sham", "noah"])
arr2.dtype

dtype('<U4')

In [ ]:
arr3 = np.array([True, False])
arr3.dtype

dtype('bool')

Importance of Datatypes in memry management and performance:-

MEMORY MANAGEMENT:-

* Memory Efficiency:

Different datatypes require different amount of memory. For example on int8 type requires 1 byte per element, while on int 64 requires 8 bytes per element. Choosing a smaller datatype (e.g., int8 or float32 over int64 or float64) can save a significant amount of memory when working with large arrays.

Example:

In [ ]:
arr_int8 = np.array([1,2,3,4,5], dtype = 'int8')
arr_int64 = np.array([1,2,3,4,5], dtype = 'int64')

arr_int8.nbytes

5

In [ ]:
arr_int64.nbytes

40

* Large Databases:- When working with large databases, using the apprpriate datatypecan reduce memory usage substantially and allow you to process larger databases on machines with limited memory resources.

2) PERFORMANCE

* Computation speed:

Smaller datatypes typically lead to faster computation since less memory is processed and accessed.. For example, operations on float32 arrays are usually faster than float64 arrays, particularly when dealing with large databases.

Example:

In [ ]:
arr1 = np.random.rand(100000000).astype('float32') # 32- bit floating point
arr2 = np.random.rand(100000000).astype('float64') # 64- bit floating point

* Memory Caching:

Smaller datatypes allow for more efficient use of the CPU's cache, which can improve the  speed of repeated cmputations. Larger datatypes may exceed the size of the CPU's cache, leading to more frequent memory access which is slower.

* Accuracy and Precision:

Smaller datatypes may results in loss of precision. For example, float32 may provides less precision than float64. In applications requires higher numerical precision(e.g. scintific simulations or financial calculations), using float64 or float128 is more appropriate to avoid rounding errors.

Example:

In [ ]:
arr_float32 = np.array([0.1,0.2,0.3], dtype = 'float32')
arr_float64 = np.array([0.1,0.2,0.3], dtype = 'float64')
print(arr_float32.sum())
print(arr_float64.sum())

0.6
0.6000000000000001


Choosing the right datatype depends upon trade-offs between memory, speed and precisin requirements for your specific application.

#5) Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Solution:

An ndarray (n-dimensional array) is the core data structture provided by the NumPy library in Python. It represents a homogenous, multidimensinal array of fixed-sized items. This means that every element in the array can have multiple dimensions(e.g.,1D,2D,3D etc.).

Key Features of ndarrays:-

1) Homogenous Data Types:

All elements in a NumPy ndarray must have the same datatype. This uniforms allows for efficient memory use and fast operatins, as there is n need for type checking during computations.

Example:



In [ ]:
arr = np.array([1,2,3,4,5], dtype = np.int32) # All elements are integers

2) Multidimensional:

* ndarray can represent arrays of any dimension, from 1D vectors to multidimensional matrices and beyond.

* The number of dimensions (for axes)is known as the rank of the array, and the size along each dimension is called its shape.

In [ ]:
arr_1 = np.array([1,2,3,4,5]) # 1D array
arr_2d = np.array([[1,2],
                   [3,4]])
arr_3d = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]]])

3) Efficient memory usage:- ndarrays are stored as the contiguous block of memory unlikePython lists, which are arrays of pointers. This efficient memory layout allows fast element access and avoids overhead from pointer dereferencing.

4) Vectorized Operations:

NumPy ndarrays support vectorized operations, which mean that operations can be applied to entire arrays at once without the need fr loops. This leads to cleaner, more readable code and faster execution.

In [ ]:
arr = np.array([1,2,3])
arr_squared = arr**2
arr_squared

array([1, 4, 9])

5)Shape Manipulation:

ndarray allow flexible reshaping without changing the data. You can change the number of dimensions or rearrange elements as needed using .reshape() method or transpose().

Example:

In [ ]:
arr = np.array([1,2,3,4,5,6])
arr_reshape = arr.reshape(2,3) # Reshape into a 2*3 array
arr_reshape

array([[1, 2, 3],
       [4, 5, 6]])

7) Slicing and Indexing:

You can access and manipulate specific elements or subarrays using slicing, similar to lists but more powerful for multi-dimensional arrays.

Example:

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
arr[0,1]

2

Differences between ndarrays from standard Python lists:

1) Homogeneity:

* ndarrays: All the elements must be of same datatype (e.g., all int32, all float64).

* Lists: Lists can store elements of different types(e.g., integers,floats, strings,etc.).

2) Memory Efficiency:

* ndarrays: Stored in a contiguous block of memory with fixed datatype, which allows efficient memory use and fast access to elements.

* Lists: Internally, lists are arrays of pointers to objects, resulting in higher memory overhead due to the storage of object references.

3) Performance:

* ndarrays: Optimized for numerical operations, especially large datasets, by performing vectorized operations that leverage compiled codde.

* Lists: Iterating through lists for element-wise operations is slower due to the dynamic typing and need for explicit loops.

4) Dimensionality:

ndarrays: Supports multi-dimensinal arrays (1D, 2D, 3D, etc.) natively and efficiently.

Lists: Only support 1D lists naturally, and you need nested lists to represent higher dimensions, which is less efficient and harder to manipulate.

5) Broadcasting:

ndarrays: support broadcasting, which allows operations on arrays of different shapes without manual resizing.

Lists: Do not supports broadcasting. You would need to manually loop or adjust dimensions.

6) Advanced Indexing and Slicing:

* ndarrays: Provide powerful slicing and indexing mechanisms for multi-dimensinal arrays.

* Lists: Only supports basic slicing for 1D lists and less intuitive methods for nested lists.

ndarray are optimized for performance, memory efficiency, and handling large-scale numerical computations, making them a better choice standard Python lists for scientific and data analysis tasks.

# 6) Analyze the performance benefits of NumPy arrays over Python list for large scale numerical operations.

Solution:

NumPy arrays offer significant performance benefits over Python lists when performing large scale numerical operations. Key aspects of how Python lists in large-scale operations are:

1) Memory efficiency layout:

NumPy arrays store data in a contiguous block of memory. All the elements are of the same datatypes, which makes memory managementmore efficient. Python lists, on the other hand arrays of pointers to objects, which means that each element is a seprate object with its own memory allocation. This leads to overhead in terms of both memory and time when accessing elements.

Example;



In [ ]:
arr = np.array([1,2,3,4,5]) # 4 integers stored contiguously in memory
Python_list = [1,2,3,4,5] # 4 integers stored as separate objects

For large datasets, the contiguous memory structure of NumPy arrays reduces the memory footprint, allowing efficient storage and processing of large-scale data.

2) Faster Element-wise operations:-
* Vectorized Operations:- NumPy supports vectorized opearations, where mathematical function are applied to entire arrays at once, rather than element by element. /this avoids the need for explicit loops and leverages low-level optimization that make computation much faster.

Example:

In [ ]:
arr= np.array([1,2,3,4,5])
result = arr**2
result

array([ 1,  4,  9, 16, 25])

In Python lists, you would need to use a loop or list comprehension to acheive the same result:

In [ ]:
python_list = [1,2,3,4,5]
result_list = [x +10 for x in python_list]
result_list()  # slower due to explicit loop

* Performance Test for Large Arrays:

In [ ]:
import time
size = 1000000
arr = np.arange(size)

start = time.time()
arr_result = arr + 1
end = time.time()
print(f"NumPy time: {end - start} seconds")

NumPy time: 0.00841069221496582 seconds


In [ ]:
size = 1000000
python_list = list(range(size))

start = time.time()
list_result = [x+1 for x in python_list]
end = time.time()
print(f"Python list time: {end - start} seconds")

Python list time: 0.14842653274536133 seconds


The NumPy opearation is much faster because it uses vectorization, whereas Python lists require explicit iteration.

3) Lower Computational Overhead:

* NumPy avoids the overhead of Python's dynamic typing, which is significant when handling large-scale data.

* Efficient Loops: NumPy uses highly optimized internal loops for operations, whereas Python lists rely on slower, interpted loops. This make NumPy a preferred choice for tasks like linear algebra, statistics and signal processing, which involve repititive operations on large datasets.

4) Broadcasting Capabilities:

NumPy allows arrays of different shapes to be used in arthimatic operations through a mechanism called as broadcasting. This avoid the need to manually reshape or expand arrays to match in size, saving both memory and computation time.

Example:

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
scaler = 10
result = arr+10
result

array([[11, 12, 13],
       [14, 15, 16]])

5) Advanced Indexing and Slicing:

* Advanced Indexing: NumPy provides advanced and efficient slicing and indexing mechanism that allow selecting specific rows, columns or subarrays from a multi-dimensional array. Python lists require nested loops or list comprehensions, which are slower and more cumbersome.

Example:

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
sub_array = arr[:2, :2]
sub_array

array([[1, 2],
       [4, 5]])

In Python lists, achieving the same result would require more complex code, and performance would degrade with larger datasets.

6) Numerical Precision and Datatypes:

* Control over datatypes: NumPy allows users to specify the datatype of array elements. This allows better control memory usage and precision. In contrast, Python lists have no built-in mechanism to specify the type of elements, leading to inconsistent memory use and less efficient computations for large scale data.

For operations where precision matters (e.g., scientific computation), having the ability to specify datatypes is crucial for maintaining accuracy while optimizing memory use.

# 7) Compare vstack() and hstack() functions in NumPy. Provide example demonstrating their usage and output.

Solution:

In NumPy, vstack() and hstack() are used to stack arrays vertically and horizontally, respectively. They are useful when you neeed to combine multiple arrays into a single on along a specific axis. Here's a detailed comparision is:

1) numpy.vstack() (Vertical Stack):

* Purpose: vstack() stacks arrays vertically along the first axis( row-wise). It combines arrays by adding them as new rows on top of one another.

* Behaviour: It requires the arrays to have the same number of columns(same width) but can differ in the number of rows.

* Syntax:



In [ ]:
numpy.vstack(tup)

* Parameter: tup- A sequence of arrays to be stacked vertically. The arrays should have the same number of columns.

Example:

In [ ]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9]])
result = np.vstack((array1, array2))
result

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

vstack() takes the two arrays and adds array2 as a new row beneath array1. The number of columns must match for this operation to succeed.

2) numpy.hstack() (Horizontal Stack):

* Purpose: hstack stacks arrays horizontally along the second axis(column- axis). It combines arrays by adding them as new columns side by side.

Behaviour: It requires the arrays to have the same number of rows (same height) but can differ in the number of columns.

Syntax:

In [ ]:
numpy.hstack(tup)

* Parameter: tup- A sequence of arrays to be stacked horizontally. The arrays should have the same number of rows.

Example:

In [ ]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8],[9,10]])
result = np.hstack((array1, array2))
result

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10]])

hstack() combines array1 and array2 by adding the columns of array2 to the right of array1. The number of rows must match for this operation to succeed.

* Comparision Between vstack() and hstack():

1) Stacking direction:

* vstack() stacks arrays vertically (row-wise), adding new rows.

* hstack() stacks arrays horizontally(column_wise), adding new columns.

2) Shape Requirements:

* vstack() requires that the arrays have same number of columns but can have different numbers of rows.

* hstack() requires that the arrays have the same number of rows but can have differentnumbers of columns.

3) Typical Use cases:

* vstack(): When you have multiple sets of data with the same number of features(columns) and want to combine them into one dataset by adding rows.

* hstack(): When you want to argument existing data with additional features (columns) for each row of data.

Both functions are convenient and efficient for concatenating arrays in differet orientations, saving from manually handling array shapes and concatenation logic.

#8) Explain the difference between fliplr() and flipud() methods in NumPy, including their effect on various array dimensions.

Solution:

In NumPy, fliplr() and flipud() are two distinst methods used to reverse the elements of an array, but they act on different axes. Heres a detailes explaination of the differences:

1) numpy.fliplr() (Flip Left-Right):

* Description: The fliplr() function reverse the order of elements along the columns of 2D array. In other words, it flips the array horizontally, swapping the columns from left to right.

* Applicable to: It only works for arrays with at least two dimensions (2D arrays and higher).

* Axis: It operates along the last axis (axis =1) i.e., the horizontal axis of a 2D array.

* Effect on array:

* The first column becomes the last column.

* The second column becomes the second-to-last column, and so on.

Example:

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
flipped_lr = np.fliplr(arr)
flipped_lr

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

2) numpy.flipud() (Flip Up-Down):

* Description: The flipud() function reverses the order of elements along the rows of a 2D array. In other words, it flips the array vertically, swapping the rows from top to bottom.

* Applicable to: It also works for arrays with at least 2 dimensions (2D arrays and higher).

* Axis: It opeartes along the first axis (axis=0) i.e., the vertical axis of a 2D array.

Effect on Array:

* The first row becomes the last row.

* The second row becomes the second-to-last row, and so on.

Example:

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
flipped_ud = np.flipud(arr)
flipped_ud

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

Behaviour with Higher Dimensions:

For higher dimension arrays:

* fliplr() will only affect the last two axes (the horizontal direction of the 2D slices).

* flipud() will affect the first two axes (the vertical direction of the 2D slices.

Both function maintain the structure of higher-dimensional arrays while flipping only the relevant 2D slices.

Effects of fliplr() and flipud() on various array dimensions:

* 1D array:

1)fliplr(): Does not work on 1D arrays and raises and error because it expects at least 2D array.

2) flipud():

In [ ]:
arr_1d = np.array([1,2,3,4,5])
flipud_1d = np.flipud(arr_1d)
flipud_1d

array([5, 4, 3, 2, 1])

* 2D Array:

1) fliplr():

In [ ]:
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                   [7,8,9]])
fliplr_2d = np.fliplr(arr_2d)
fliplr_2d

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

2) flipud():

In [ ]:
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                   [7,8,9]])
flipud_2d = np.flipud(arr_2d)
flipud_2d

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

* 3D Array:

1) fliplr():

In [ ]:
arr_3d = ([[[1,2,3],
            [4,5,6]],
            [[7,8,9],
            [10,11,12]]])
fliplr_3d = np.fliplr(arr_3d)
fliplr_3d

array([[[ 4,  5,  6],
        [ 1,  2,  3]],

       [[10, 11, 12],
        [ 7,  8,  9]]])

2) flipud():

In [ ]:
arr_3d = ([[[1,2,3],
            [4,5,6]],
            [[7,8,9],
            [10,11,12]]])
flipud_3d = np.flipud(arr_3d)
flipud_3d

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

* Higher Dimensional Arrays (4D,5D, etc):

Both fliplr() and flipud() will work similarly in higher-dimensional arrays by operating on the 2D slices within these higher dimensions.

Example: In a 4D array, it will operate on each 2D slice from the third and fourth dimension.

In [ ]:
arr_4d = np.random.rand(2,2,3,4)
fliplr_4d = np.fliplr(arr_4d)
fliplr_4d

array([[[[0.39793318, 0.30816433, 0.13593531, 0.59114123],
         [0.04130405, 0.46014642, 0.481831  , 0.58460866],
         [0.66100072, 0.3667484 , 0.9413822 , 0.63184474]],

        [[0.8550133 , 0.62686774, 0.22399998, 0.05442906],
         [0.2280159 , 0.42500643, 0.05096977, 0.77881707],
         [0.53807761, 0.03868975, 0.4593695 , 0.56988095]]],


       [[[0.46413019, 0.10551424, 0.90262057, 0.9788467 ],
         [0.37190074, 0.40466285, 0.39904408, 0.91402479],
         [0.4741752 , 0.10743144, 0.86943799, 0.85761773]],

        [[0.52398435, 0.21809003, 0.81598715, 0.64793009],
         [0.07178121, 0.06222541, 0.83944664, 0.39415189],
         [0.32984744, 0.62370523, 0.95317297, 0.64714614]]]])

In [ ]:
arr_4d = np.random.rand(2,2,3,4)
flipud_4d = np.flipud(arr_4d)
flipud_4d

array([[[[0.2657777 , 0.08894719, 0.40679903, 0.68859852],
         [0.53963761, 0.12579467, 0.36002314, 0.83566875],
         [0.73497766, 0.96348083, 0.43960106, 0.17206641]],

        [[0.6065434 , 0.46206862, 0.76611425, 0.50390065],
         [0.20946465, 0.57655767, 0.8877946 , 0.78599283],
         [0.38643119, 0.23451487, 0.07487145, 0.44020208]]],


       [[[0.60365388, 0.18937692, 0.50264691, 0.27466533],
         [0.16247613, 0.9379582 , 0.48740875, 0.23761421],
         [0.30150422, 0.22711549, 0.35531452, 0.92790768]],

        [[0.15294989, 0.10273525, 0.20587797, 0.2778195 ],
         [0.71672762, 0.51769643, 0.41327943, 0.92197519],
         [0.40557055, 0.80880332, 0.58376969, 0.40078245]]]])

#9) Discuss the functionality of array_split() method in NumPy. How does it handles uneven splits?

Solution:

In Numpy, the array_split() method is used to split an array into multiple sub-arrays along a specified axis. It is similar to the split method but with a key difference: array_split() can handle uneven splits, meaning it does nor require that the array be divisible by the number of splits.

Key Features of array_split():

1) General Usage: It splits an array into sub-arrays, dividing the array into approximately equal parts.

2) Uneven Splits: If the array cannot be divided evenly, array_split() ensures that the sub-arrays are as balanced as possible, meaning some of the sub-arrays will have more elements than others.

3) Axis: The splitting can be done along a specific axis (default is axis=0).

Syntax:


In [ ]:
numpy.array_split(ary, indices_or_sections, axis=0)

* ary: The input array you want to split.

* indices_or_section: If an integer, it defines the number of equal splits. If a list, it defines the indices at which to split.

* Axis: The axis along which to split the array (default is axis=0).

Examples:

1) Even Splitting (when the number of splits evenly divides the array):

In [ ]:
arr = np.arange(12)
splits = np.array_split(arr, 4)
for split in splits:
  print(split)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


2) Uneven Splitting (when the array cannot be evenly divided by the number of splits):

In [ ]:
arr = np.arange(10)
splits = np.array_split(arr, 3)
for split in splits:
  print(split)

[0 1 2 3]
[4 5 6]
[7 8 9]


Handling Uneven Splits:

* When the number of elements in the array does not divide evenly by the specified number of splits, array_split() distributes the elements as evenly as possible.

* The earlier sub-arrays will recieve one extra element if necessary.

Splitting Along Different Axes:

Example (2D Array):

In [ ]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])
splits = np.array_split(arr_2d, 3, axis=0)
for split in splits:
  print(split)

[[1 2 3]
 [4 5 6]]
[[7 8 9]]
[[10 11 12]]


The 2D array with 4 rows is split into 3 parts along axis=0(rows), resulting in one part with 2 rows and the other two with 1 row each.

Example with Custom Indices:

If you want to split the array at specific indicesinstead of requesting a number of splits, you can pass a listof indices.

In [ ]:
arr = np.arange(10)
splits = np.array_split(arr, [3,5])
for split in splits:
  print(split)

[0 1 2]
[3 4]
[5 6 7 8 9]


The array is split at index 3 and index 5:

 * The first sub-array has elements [0,1,2] (from index 1 to 2).

 * The second sub-array has elements [3,4] (from index 3 to 4).

 * The third sub-array has elements [5,6,7,8,9] (from index 5 onwards).

 # 10) Explain the concepts of vectorization and broadcasting in NumPy.How do they contribute to efficient array operations?

 Solution:

 Vectorization and Broadcasting are two key concepts in NumPy that enable efficient and optimized data operations. They help avoid explicit loops, making operation faster by utilizing low level optimization and taking advantage of hardware capabilities like SIMD (Single Instruction, Multiple Data).

 Vectorization:

 Definition:

 Vectorization refers to performing operations on entire arrays(vectors and matrices) element-wise, without using explicit loops. In NumPy, opearations like addition, substraction, multiplication, and other mathematical functions are automatically vectorized, allowing them to be applied to all elements of an array at once.

 Mechanism of Vectorization:

 * Instead of writing a loop to perform operations element-by-element, NumPy allows you to perform operations directly on the entire array.

 Example:

 Without vectorization (using explicit loops):



In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

result = np.empty_like(a)
for i in range(len(a)):
  result[i] = a[i] + b[i]
print(result)

[ 6  8 10 12]


With vectorization:

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

result = a+b   #vectorized operation
print(result)

[ 6  8 10 12]


Benefits of Vectorization:

1) Performance: Vectorized operations are significantly faster than explicit loops because NumPy executes the operations in compliled, low-level code rather than in Python's interpreter.

2) Simplicity: Code is easier to write and read because the operations are expressed in a high-level manner.

3) Optimization: NumPy automatically optmizes operations for the hardware.

Broadcasting:

Definition:

Broadcasting is a mechanism in NumPy that allows arrays with different shapes to be combined in arithmatic operations. It works by streatching smaller arrays along specific axes so that they match the dimensions of the larger array.

Mechanism of Broadcasting:

When two arrays with different shapes are used in an operation, NumPy tries to "Broadcast" the smaller array to match the shape of the larger one. This allows operations like addition,multiplication, etc., to be applied without the need to explicitly reshape arrays.

Broadcasting Rules:

1) Same shape: If the array have the same shape, they can be operated element-wise directly.

2) Dimension alignment: If arrays have different shapes, NumPy compares their dimensions from right to left. Arrays are compatible if:

* They have the same size in a dimension.

* One of the array has a size of 1 in a dimension (which can be "stretched").

Example:



In [ ]:
a = np.array([1,2,3])
b = np.array([[10], [20], [30]])
result = a+b
result

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

* a is reshaped from (3,) to (1,3) for broadcasting.

* b is reshaped from (3,1) to (3,3) by "stretching" along the last dimension.

Example with Scalar:

A scalar value can be broadcast to an entire array. For example:

In [ ]:
a = np.array([1,2,3])
result = a + 5
result

array([6, 7, 8])

The scalar 5 is broadcast to the shape of a, and the operation is applied element-wise.

Benefits of Broadcasting:

1) Memory Efficiency: Broadcasting avoids the need to create copies of arrays, especially when combining large arrays with smaller ones.

2) Concise Code: Broadcasting allows for concise code without the need to explicit reshaping or replicatin of arrays.

3) Performance: Since broadcasting operates on the underlying data without making extra copies, it is memory-efficient and can significantly improve performance for large databases.

Example Combining Vectorization and Broadcasting:

In [ ]:
a = np.array([1,2,3])            # Shape: (3,)
b = np.array([[10], [20], [30]]) # Shape: (3,1)
result = a*b # Broadcasting allows element-wise multiplication between arrays of different shapes
result

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In this example:

* Vectorization allows the element-wise multiplication between the arrays.

* Broadcasting enables the multiplication by alighning the shapes of the two arrays.

Both vectorization and broadcasting work together to boost the performance of array operation in NumPy, taking advantage of hardware-level optimizations and simplifying the code.